-- ============================================================
-- MusicZone - Script PostgreSQL/Supabase
-- ============================================================

-- Ejecutar en Supabase SQL Editor o con psql conectado a la base postgres.
-- No se usa CREATE DATABASE ni USE porque Supabase ya provee la base.

DROP TABLE IF EXISTS cancion_playlist;
DROP TABLE IF EXISTS playlist;
DROP TABLE IF EXISTS cancion;
DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS artista;
DROP TABLE IF EXISTS usuario;
DROP FUNCTION IF EXISTS set_fecha_actualizacion();

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre_usuario VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    correo VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uq_nombre_usuario UNIQUE (nombre_usuario),
    CONSTRAINT uq_usuario_correo UNIQUE (correo)
);

CREATE TABLE artista (
    id_artista BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(150) NOT NULL,
    genero VARCHAR(80),
    pais VARCHAR(80),
    bio TEXT,
    perfil_url VARCHAR(500),

    CONSTRAINT pk_artista PRIMARY KEY (id_artista)
);

CREATE TABLE album (
    id_album BIGINT GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(200) NOT NULL,
    id_artista BIGINT NOT NULL,
    year_lanzamiento INTEGER,
    portada_url VARCHAR(500),

    CONSTRAINT pk_album PRIMARY KEY (id_album),
    CONSTRAINT fk_album_artista FOREIGN KEY (id_artista)
        REFERENCES artista(id_artista)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE cancion (
    id_cancion BIGINT GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(200) NOT NULL,
    id_artista BIGINT NOT NULL,
    id_album BIGINT,
    duracion_segundos INTEGER,
    numero_track INTEGER,
    genero VARCHAR(80),
    year_lanzamiento INTEGER,

    CONSTRAINT pk_cancion PRIMARY KEY (id_cancion),
    CONSTRAINT fk_cancion_artista FOREIGN KEY (id_artista)
        REFERENCES artista(id_artista)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_cancion_album FOREIGN KEY (id_album)
        REFERENCES album(id_album)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE playlist (
    id_playlist BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(150) NOT NULL,
    id_usuario BIGINT NOT NULL,
    descripcion TEXT,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_playlist PRIMARY KEY (id_playlist),
    CONSTRAINT fk_playlist_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION set_fecha_actualizacion()
RETURNS TRIGGER AS $$
BEGIN
    NEW.fecha_actualizacion = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_playlist_fecha_actualizacion
BEFORE UPDATE ON playlist
FOR EACH ROW
EXECUTE FUNCTION set_fecha_actualizacion();

CREATE TABLE cancion_playlist (
    id_playlist BIGINT NOT NULL,
    id_cancion BIGINT NOT NULL,
    posicion INTEGER,
    fecha_agregada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_cancion_playlist PRIMARY KEY (id_playlist, id_cancion),
    CONSTRAINT uq_playlist_posicion UNIQUE (id_playlist, posicion),
    CONSTRAINT fk_ps_playlist FOREIGN KEY (id_playlist)
        REFERENCES playlist(id_playlist)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_ps_cancion FOREIGN KEY (id_cancion)
        REFERENCES cancion(id_cancion)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX idx_cancion_titulo ON cancion(titulo);
CREATE INDEX idx_cancion_genero ON cancion(genero);
CREATE INDEX idx_artista_nombre ON artista(nombre);
CREATE INDEX idx_playlist_usuario ON playlist(id_usuario);
CREATE INDEX idx_album_artista ON album(id_artista);

INSERT INTO usuario (nombre_usuario, password, correo) VALUES
('admin', '$2a$10$lBgTcru/nnyhkKAlofGizuwX5QPjo2PQL4BksSzx9Tv7tcRKz0mti', 'admin@musiczone.com'),
('test', '$2a$10$lLpjPaFsWcuoQgV6Z49GP.4OPMJRpC6iJTemor8xwg0g8tyxneuG.', 'test@test.com');

INSERT INTO artista (nombre, genero, pais, bio) VALUES
('The Beatles', 'Rock', 'Reino Unido', 'Banda legendaria de Liverpool formada en 1960. Redefinieron la musica popular del siglo XX.'),
('Queen', 'Rock', 'Reino Unido', 'Banda de rock britanica liderada por Freddie Mercury, conocida por su teatralidad y virtuosismo.'),
('Bad Bunny', 'Reggaeton', 'Puerto Rico', 'Artista urbano puertorriqueno, uno de los mas escuchados del mundo en la ultima decada.'),
('Taylor Swift', 'Pop', 'Estados Unidos', 'Cantautora y compositora multipremiada, conocida por sus albumes narrativos y re-grabaciones.'),
('Carlos Vives', 'Vallenato', 'Colombia', 'Maximo exponente del vallenato moderno, ganador de multiples Grammy y Grammy Latino.'),
('Daft Punk', 'Electronic', 'Francia', 'Duo de musica electronica parisino, pioneros del French House y la musica dance de los 90s.');

INSERT INTO album (titulo, id_artista, year_lanzamiento, portada_url) VALUES
('Abbey Road', 1, 1969, 'https://upload.wikimedia.org/wikipedia/en/4/42/Beatles_-_Abbey_Road.jpg'),
('Let It Be', 1, 1970, NULL),
('A Night at the Opera', 2, 1975, NULL),
('Greatest Hits', 2, 1981, NULL),
('Un Verano Sin Ti', 3, 2022, NULL),
('YHLQMDLG', 3, 2020, NULL),
('1989', 4, 2014, NULL),
('Midnights', 4, 2022, NULL),
('Clasicos de la Provincia', 5, 1993, NULL),
('Random Access Memories', 6, 2013, NULL);

INSERT INTO cancion (titulo, id_artista, id_album, duracion_segundos, numero_track, genero, year_lanzamiento) VALUES
('Come Together', 1, 1, 259, 1, 'Rock', 1969),
('Something', 1, 1, 182, 2, 'Rock', 1969),
('Here Comes the Sun', 1, 1, 185, 8, 'Rock', 1969),
('Let It Be', 1, 2, 243, 6, 'Rock', 1970),
('Hey Jude', 1, NULL, 431, NULL, 'Rock', 1968),
('Bohemian Rhapsody', 2, 3, 354, 11, 'Rock', 1975),
('Love of My Life', 2, 3, 213, 9, 'Rock', 1975),
('We Will Rock You', 2, 4, 122, 1, 'Rock', 1977),
('We Are the Champions', 2, 4, 179, 2, 'Rock', 1977),
('Don''t Stop Me Now', 2, 4, 209, 5, 'Rock', 1978),
('Moscow Mule', 3, 5, 237, 2, 'Reggaeton', 2022),
('Me Porto Bonito', 3, 5, 178, 4, 'Reggaeton', 2022),
('Titi Me Pregunto', 3, 5, 240, 6, 'Reggaeton', 2022),
('Safaera', 3, 6, 290, 5, 'Reggaeton', 2020),
('Yo Perreo Sola', 3, 6, 195, 11, 'Reggaeton', 2020),
('Shake It Off', 4, 7, 219, 6, 'Pop', 2014),
('Blank Space', 4, 7, 231, 2, 'Pop', 2014),
('Style', 4, 7, 231, 3, 'Pop', 2014),
('Anti-Hero', 4, 8, 200, 1, 'Pop', 2022),
('Lavender Haze', 4, 8, 202, 2, 'Pop', 2022),
('La Bicicleta', 5, 9, 227, 1, 'Vallenato', 1993),
('Frio Frio', 5, 9, 198, 3, 'Vallenato', 1993),
('El Amor de Mi Tierra', 5, 9, 210, 5, 'Vallenato', 1993),
('Get Lucky', 6, 10, 369, 8, 'Electronic', 2013),
('Instant Crush', 6, 10, 337, 4, 'Electronic', 2013),
('Lose Yourself to Dance', 6, 10, 345, 7, 'Electronic', 2013);

INSERT INTO playlist (nombre, id_usuario, descripcion) VALUES
('Mis Clasicos', 1, 'Las mejores canciones de todos los tiempos'),
('Workout Mix', 2, 'Energia pura para entrenar'),
('Relax & Chill', 2, 'Canciones para relajarse');

INSERT INTO cancion_playlist (id_playlist, id_cancion, posicion) VALUES
(1, 6, 1),
(1, 1, 2),
(1, 3, 3),
(1, 8, 4),
(1, 9, 5),
(1, 5, 6),
(1, 24, 7),
(2, 8, 1),
(2, 9, 2),
(2, 10, 3),
(2, 16, 4),
(2, 12, 5),
(2, 15, 6),
(3, 3, 1),
(3, 2, 2),
(3, 7, 3),
(3, 25, 4),
(3, 22, 5);
