spring.application.name=musiczone-backend

spring.data.mongodb.uri=mongodb+srv://angelalozanouis2022:kDSuRsKqbXkN3WyH@cluster0.aublw.mongodb.net/musiczone?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=musiczone

springdoc.swagger-ui.path=/swagger-ui.html

server.port=8081
