spring.application.name=musiczone-backend

# ── Base de datos ──────────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/musiczone?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=An29#Lo*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA / Hibernate ────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ── Servidor ───────────────────────────────────────────────
server.port=8080


